net = "REPLACEME"
cpu = "REPLACEME"
mem = "REPLACEME"
dsk = "REPLACEME"
api1 = "REPLACEME"
api2 = "REPLACEME"
api3 = "REPLACEME"
api4 = "REPLACEME"
url1 = "REPLACEME"
url2 = "REPLACEME"
url3 = "REPLACEME"
url4 = "REPLACEME"
urlp1 = "REPLACEME"
urlp2 = "REPLACEME"
urlp3 = "REPLACEME"
urlp4 = "REPLACEME"
health1 = "REPLACEME"
health2 = "REPLACEME"
health3 = "REPLACEME"
health4 = "REPLACEME"
